### ISSUE TITLE
Deep Learning for NLP course

### ISSUE THREAD

**Issue by jvdzwaan** [nlesc-sigs/nlp-sig#2]
I'd like to do the Stanford Natural Language Processing with Deep Learning course for my T&D this year. Anyone interested in joining me? We could do it with the whole sig, so, watch the videos and do the assignments, or find some other arrangement if that works for more people.

http://web.stanford.edu/class/cs224n/

**Comment by eriktks** [comment]
This proposal was accepted, see: https://github.com/NLeSC/natural-language-processing-sig/blob/master/nlp-deeplearning.md
